# network architecture
# encoder related
input_size: 80
#frontend: wav_frontend
#frontend_conf:
#    fs: 16000
#    window: hamming
#    n_mels: 80
#    frame_length: 25
#    frame_shift: 10
#    dither: 0.0
#    lfr_m: 5
#    lfr_n: 1
feature_transform:
    cmvn_file: res/vad.mvn
    lfr_m: 5
    lfr_n: 1

model: fsmnvad
encoder: fsmn
encoder_conf:
    input_dim: 400
    input_affine_dim: 140
    fsmn_layers: 4
    linear_dim: 250
    proj_dim: 128
    lorder: 20
    rorder: 0
    lstride: 1
    rstride: 0
    output_affine_dim: 140
    output_dim: 248

# optimization related
accum_grad: 2
grad_clip: 5
patience: none
max_epoch: 50
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
   lr: 0.0001
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 10000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

log_interval: 50

#normalize: global_mvn
batch_type: length
batch_bins: 25000 
num_workers: 16

dataset_conf:
    #data_names: speech,text
    #data_types: kaldi_ark,kaldi_ark
    shuffle: True
    shuffle_conf:
        shuffle_size: 2048
        sort_size: 500
   # batch_conf:
   #     batch_type: length
   #     batch_size: 128
   # num_workers: 8
